// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPPt8dMWo6xNYmNZ4cpqqsxegBiLAjSY',
    appId: '1:272696026835:android:765f5b27646abe63f01626',
    messagingSenderId: '272696026835',
    projectId: 'engexpert-app',
    storageBucket: 'engexpert-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfCQJksbjB2UG8NlEk0l7JNfOLaRXx0Y',
    appId: '1:272696026835:ios:f8f0786207d8615ff01626',
    messagingSenderId: '272696026835',
    projectId: 'engexpert-app',
    storageBucket: 'engexpert-app.appspot.com',
    androidClientId: '272696026835-lg6kqflm31u836lcjdtisegjoue7ifc4.apps.googleusercontent.com',
    iosClientId: '272696026835-0mqjlma057r20qd0ahb5jbc08tq2j4ue.apps.googleusercontent.com',
    iosBundleId: 'com.engexpert.app',
  );
}
